### PR TITLE
added option to filter the output by the level of the spot

### PR DESCRIPTION
**Pull request by paulovitorbal**
Related with issue: #12 

I added an array with the values that are possible to $cate.
And filtered it by the input passed by the arg --level.

### CODE REVIEW

**Comment by paulovitorbal** [comment]
I just added another commit.

**Comment by monque** [comment]
Thank you. Could you make this commit pass those auto-checks?

**Comment by paulovitorbal** [comment]
I finally made it pass everything.

Sorry, it was the first time that I used the styleci and travis.

**Comment by monque** [comment]
It seems that the configuration on Style-CI's website did not apply for your forked project.

I've already added some rules to make Style-CI more less strictly. It is [here]( https://github.com/monque/PHP-Migration/blob/master/.styleci.yml).

Thanks for your hard work!

**Pull request merged**
